// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protofile.proto
#ifndef GRPC_protofile_2eproto__INCLUDED
#define GRPC_protofile_2eproto__INCLUDED

#include "protofile.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace myproto {

class MyService final {
 public:
  static constexpr char const* service_full_name() {
    return "myproto.MyService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::myproto::Answer* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>> AsyncGetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>>(AsyncGetMaxOneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>> PrepareAsyncGetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>>(PrepareAsyncGetMaxOneRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>* AsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myproto::Answer>* PrepareAsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::myproto::Answer* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myproto::Answer>> AsyncGetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myproto::Answer>>(AsyncGetMaxOneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myproto::Answer>> PrepareAsyncGetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myproto::Answer>>(PrepareAsyncGetMaxOneRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::myproto::Answer>* AsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::myproto::Answer>* PrepareAsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMaxOne_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMaxOne(::grpc::ServerContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMaxOne() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMaxOne(::grpc::ServerContext* context, ::myproto::Numbers* request, ::grpc::ServerAsyncResponseWriter< ::myproto::Answer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMaxOne<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetMaxOne() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::myproto::Numbers, ::myproto::Answer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::myproto::Numbers* request, ::myproto::Answer* response) { return this->GetMaxOne(context, request, response); }));}
    void SetMessageAllocatorFor_GetMaxOne(
        ::grpc::experimental::MessageAllocator< ::myproto::Numbers, ::myproto::Answer>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::myproto::Numbers, ::myproto::Answer>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMaxOne(
      ::grpc::CallbackServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMaxOne(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetMaxOne<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetMaxOne<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMaxOne() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMaxOne() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMaxOne(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetMaxOne() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMaxOne(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMaxOne(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMaxOne(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMaxOne : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMaxOne() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::myproto::Numbers, ::myproto::Answer>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::myproto::Numbers, ::myproto::Answer>* streamer) {
                       return this->StreamedGetMaxOne(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMaxOne() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMaxOne(::grpc::ServerContext* /*context*/, const ::myproto::Numbers* /*request*/, ::myproto::Answer* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMaxOne(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::myproto::Numbers,::myproto::Answer>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMaxOne<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMaxOne<Service > StreamedService;
};

}  // namespace myproto


#endif  // GRPC_protofile_2eproto__INCLUDED
