// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protofile.proto

#include "protofile.pb.h"
#include "protofile.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace myproto {

static const char* MyService_method_names[] = {
  "/myproto.MyService/GetMaxOne",
};

std::unique_ptr< MyService::Stub> MyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MyService::Stub> stub(new MyService::Stub(channel));
  return stub;
}

MyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetMaxOne_(MyService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MyService::Stub::GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::myproto::Answer* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetMaxOne_, context, request, response);
}

void MyService::Stub::experimental_async::GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetMaxOne_, context, request, response, std::move(f));
}

void MyService::Stub::experimental_async::GetMaxOne(::grpc::ClientContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetMaxOne_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::myproto::Answer>* MyService::Stub::PrepareAsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::myproto::Answer>::Create(channel_.get(), cq, rpcmethod_GetMaxOne_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::myproto::Answer>* MyService::Stub::AsyncGetMaxOneRaw(::grpc::ClientContext* context, const ::myproto::Numbers& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMaxOneRaw(context, request, cq);
  result->StartCall();
  return result;
}

MyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyService::Service, ::myproto::Numbers, ::myproto::Answer>(
          [](MyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::myproto::Numbers* req,
             ::myproto::Answer* resp) {
               return service->GetMaxOne(ctx, req, resp);
             }, this)));
}

MyService::Service::~Service() {
}

::grpc::Status MyService::Service::GetMaxOne(::grpc::ServerContext* context, const ::myproto::Numbers* request, ::myproto::Answer* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace myproto

